Updated bundled FFX build to be current with the Force Field X website. The JDK was also updated from 21 to 25 in the conda environment.

diff --git a/ffx-1.0.0/bin/ffxc b/ffx-1.0.0/bin/ffxc
--- a/ffx-1.0.0/bin/ffxc
+++ b/ffx-1.0.0/bin/ffxc
@@ -5,7 +5,7 @@
 # 
 # Description: Force Field X - Software for Molecular Biophysics.
 # 
-# Copyright: Copyright (c) Michael J. Schnieders 2001-2024.
+# Copyright: Copyright (c) Michael J. Schnieders 2001-2026.
 # 
 # This file is part of Force Field X.
 # 
@@ -137,17 +137,21 @@ if [ -x "$awkCmd" ]; then
     fi
 fi
 
-# Detect JDK version; disallow JDKs other than 21 up to 23.
+# Detect JDK version; disallow JDKs other than 25 up to 26.
 if [ $hasAwkSed ]; then
     JVERS="$(java -version 2>&1 | awk '/version/ {print $3;}' | sed 's/\"//g')"
     JVFIRST="$(echo "$JVERS" | awk 'BEGIN { FS = "[.-]"; } { print $1 }')"
 
-    if [ "$JVFIRST" -lt 21 ] || [ "$JVFIRST" -gt 23 ]; then
-        echo " Illegal Java version detected (${JVERS}). Please use JDK 21 through 23." 1>&2
+    if [ "$JVFIRST" -lt 25 ] || [ "$JVFIRST" -gt 26 ]; then
+        echo " Illegal Java version detected (${JVERS}). Please use JDK 25 through 26." 1>&2
     fi
 
-    EXTRA_JVM_ARGUMENTS="${EXTRA_JVM_ARGUMENTS} --add-opens=java.desktop/java.awt=ALL-UNNAMED --add-exports=java.base/java.lang=ALL-UNNAMED --add-exports=java.desktop/sun.awt=ALL-UNNAMED --add-exports=java.desktop/sun.java2d=ALL-UNNAMED"
+    EXTRA_JVM_ARGUMENTS="${EXTRA_JVM_ARGUMENTS} --add-opens=java.desktop/java.awt=ALL-UNNAMED --add-exports=java.base/java.lang=ALL-UNNAMED --add-exports=java.desktop/sun.awt=ALL-UNNAMED --add-exports=java.desktop/sun.java2d=ALL-UNNAMED --enable-native-access=ALL-UNNAMED"
 
+    if [ "$JVFIRST" -gt 23 ]; then
+        EXTRA_JVM_ARGUMENTS="${EXTRA_JVM_ARGUMENTS} -XX:+UnlockExperimentalVMOptions -XX:+UseCompactObjectHeaders"
+    fi
+ 
     nvccComm='which nvcc'
     hasNVCC=''
     if [ -x "$nvccComm" ]; then
@@ -164,7 +168,7 @@ if [ $hasAwkSed ]; then
       fi
     fi
 else
-    echo " The JRE and CUDA toolkit versions could not be autodetected. Please use JDK 21 through 23 and (optionally) CUDA toolkit 11.1 or later."
+    echo " The JRE and CUDA toolkit versions could not be autodetected. Please use JDK 25 through 26 and (optionally) CUDA toolkit 11.1 or later."
 fi
 
 # For Cygwin, switch paths to Windows format before running java
@@ -186,8 +190,6 @@ then
   [ -n "$REPO" ] && REPO=$(cygpath --path --unix "$REPO")
   CLASSPATH=$(echo $CLASSPATH | sed 's/ /:/g')
 fi
-
-EXTRA_JVM_ARGUMENTS="${EXTRA_JVM_ARGUMENTS}"
 
 # This is for trying to use the GraalVM native image generation
 # EXTRA_JVM_ARGUMENTS="${EXTRA_JVM_ARGUMENTS} -agentlib:native-image-agent=config-merge-dir=${BASEDIR}/bin/META-INF/native-image"
